### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by ktiwari9** [ScazLab/baxter_tictactoe#1]
Hey there,
I am trying use you vacuum_gripper package. I want to make a simple pick and place scheme for baxter using a vacuum gripper.I am using ROS Groovy.This is what I did so far :-
1.) Added the 2 _.cpp files into the src folder and added vacuum_gripper.h file into my include folder.
2.) In the CMakeLists file, I added executable and target_link_library lines and I ran catkin_make from the root of the package. 
I get the following error  :
In file included from /home/baxter/Kshitij/baxter_workspace/src/baxter_inspace/vacuum_gripper/src/vacuum_gripper.cpp:1:0:
/home/baxter/Kshitij/baxter_workspace/src/baxter_inspace/vacuum_gripper/include/vacuum_gripper/vacuum_gripper.h:10:38: fatal error: baxter_msgs/GripperState.h: No such file or directory
compilation terminated.
make[2]: *_\* [baxter_inspace/vacuum_gripper/CMakeFiles/vacuum_gripper.dir/src/vacuum_gripper.cpp.o] Error 1
make[1]: **\* [baxter_inspace/vacuum_gripper/CMakeFiles/vacuum_gripper.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

It seems like it doesnt find the gripperState.h file. 
Any suggestions on how to fix this ?
Please advise.

**Comment by alvarokas** [comment]
Him
Maybe you are working with a different version of Baxter firmware, or you don't have installed all packages you need. Make sure where Baxter messages are defined and maybe you'll have to change some include paths.

Best.

**Comment by alecive** [comment]
Closing because not actively discussed since 1.5 years ago.
