### ISSUE TITLE
Automatically detect board & cells

### ISSUE THREAD

**Issue by JohnAmadeo** [ScazLab/baxter_tictactoe#10]
Note:
- Detection of board & cells was partially incorporated into the master branch after merging the merge-package branch

To-do: 
- Send board data as service 
- Determine what to do w/ old way of using board data (saving it in ttt_board.xml and loading it)  
- Update documentation to reflect changes 
- FIx bug (currently cells_definition_auto node crashes board is not in camera's view upon launch
- (currently program doesn't work if pieces already on board) maybe have some kind of error message to user to remove pieces?

**Comment by alecive** [comment]
@JohnAmadeo is everything in this list fixed with the closing of #11 ?
