### ISSUE TITLE
Non-blocking ArmCtrl::serviceCb and action server

### ISSUE THREAD

**Issue by shrine79** [ScazLab/baxter_tictactoe#24]
@alecive The current arm service provided in baxter_collaboration::ArmCtrl class is blocking, and in turn the ArmCtrl::serviceCb() is blocking as well. It gave me hardship when I was trying to move both arms at the same time or make Baxter doing other social actions at the same time. I made an non-block arm server to do the job in worker threads and join them later in user code.  However I feel an action server could be a better solution. 

Maybe baxter_collaboration is the better place for this issue. Feel free to move it.

**Comment by alecive** [comment]
A service callback is blocking by definition. You should change ROS to change that. What did you do in order to overcome this issue exactly? Where does the code blocks? If you can share some code snippets it would be great.

**Comment by alecive** [comment]
Action server might not be a bad idea, but again it requires some time (which I don't have right now).

**Comment by shrine79** [comment]
@alecive You are right that a ROS service is blocking by definition. Plus Baxter SDK expects to receive joint command at 5Hz minimum, which requires the callback function keeping sending joint command, and this is blocking. 

Quote: 
> "A control rate timeout is also enforced at this motor controller layer. This states that if a new 'JointCommand' message is not received within the specified timeout (0.2 seconds, or 5Hz), the robot will 'Timeout'. When the robot 'Times out', the current control mode is exited, reverting back to position control mode where the robot will command (hold) it's current joint angles. "


 What I did is a temporary patch up to make the request to server return ASAP by making the service callback function return ASAP. It's not non-blocking indeed but quite close. The user code checks the internal controller state in RobotInterface class later to determine the current state of the service and joins worker threads. My fix is definitely undesirable and only works where arm controller and tictactoeBrain are running in the same node. 

An action server would make user code nice and neat.

**Comment by alecive** [comment]
I agree with you. I'll see if I find some time to work on this. Basically what I have right now is a sort of action server internal to a node, it's just a matter of improving it a bit I think.

**Comment by alecive** [comment]
I am closing as wontfix right now since I don't have time. Can you please me link me to your temporary patch so that I can understand it a little bit more? Thanks!
