### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by alecive** [ScazLab/baxter_tictactoe#3]
After doing a `catkin_make clean` to my workspace, the repo does not compile any more. Here is the output:

```
...
/home/alecive/code/catkin_ws/src/baxter_tictactoe/ttt_board_sensor/src/tictactoe_board_display/board_scheme.cpp:9:40: fatal error: ttt_board_sensor/ttt_board.h: No such file or directory
 #include "ttt_board_sensor/ttt_board.h"
                                        ^
compilation terminated.
In file included from /home/alecive/code/catkin_ws/src/baxter_tictactoe/tictactoe/src/vacuum_gripper/vacuum_gripper.cpp:1:0:
/home/alecive/code/catkin_ws/src/baxter_tictactoe/tictactoe/src/vacuum_gripper/vacuum_gripper.h:8:47: fatal error: baxter_core_msgs/EndEffectorState.h: No such file or directory
 #include <baxter_core_msgs/EndEffectorState.h>
                                               ^
compilation terminated.
In file included from /home/alecive/code/catkin_ws/src/baxter_tictactoe/ttt_board_sensor/src/ttt_cells.h:21:0,
                 from /home/alecive/code/catkin_ws/src/baxter_tictactoe/ttt_board_sensor/src/ttt_cells.cpp:1:
/home/alecive/code/catkin_ws/src/baxter_tictactoe/ttt_board_sensor/include/ttt/ttt_definitions.h:7:40: fatal error: ttt_board_sensor/ttt_board.h: No such file or directory
 #include "ttt_board_sensor/ttt_board.h"
                                        ^
compilation terminated.
In file included from /home/alecive/code/catkin_ws/src/baxter_tictactoe/tictactoe/src/robot_state/robot_state.cpp:1:0:
/home/alecive/code/catkin_ws/src/baxter_tictactoe/tictactoe/src/robot_state/robot_state.h:5:44: fatal error: baxter_core_msgs/AssemblyState.h: No such file or directory
 #include <baxter_core_msgs/AssemblyState.h>
                                            ^
compilation terminated.
...
```

I was going to debug it, and I didn't find the `ttt_board.h` file anywhere. @omangin I remember that you moved some files here and there. Is it possible that this is one of them? Maybe we did something wrong during the pull request and we lose some commits.

**Comment by alecive** [comment]
Or is `ttt_board.h` automatically generated from `ttt_board.msg` in some obscure ros way to handle `msg` files?

**Comment by alecive** [comment]
The answer is yes, because apparently `rosmsg` finds it and there is a `ttt_board.h` in my install folder:

```
[alecive@malakim]$ rosmsg show ttt_board_sensor/ttt_board 
uint8 EMPTY=0
uint8 BLUE=1
uint8 RED=2
uint8 UNDEFINED=3
std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
uint8[9] data
```

Now I have to understand why it does not find it!

**Comment by alecive** [comment]
It seems that it does not find the header files into `catkin_ws/install/include`.

**Comment by omangin** [comment]
Yes, if it is generated, it should be handled by this line (as a catkin exported targets): https://github.com/ScazLab/baxter_tictactoe/blob/master/ttt_board_sensor/CMakeLists.txt#L66
The message generation is supposed to be triggered by: https://github.com/ScazLab/baxter_tictactoe/blob/master/ttt_board_sensor/CMakeLists.txt#L25-L32

**Comment by alecive** [comment]
Closing because apparently by compiling the two packages separately the issue does not arise. This will eventually disappear when we will have a single package for them.
